export const SETPEOPLE = 'SET_PEOPLE';
export const SETERROR = 'SET_ERROR';
export const FILTERBYNAME = 'FILTER_BY_NAME';
export const SETSELECTEDNATIONALITY = 'SET_SELECTED_NATIONALITY';
export const SETSELECTEDGENDER = 'SET_SELECTED_GENDER';
export const CLEARFORM = 'CLEAR_FORM';
export const CLEARDATA = 'CLEAR_DATA';
export const STARTLOADING = 'START_LOADING';
export const FINISHLOADING = 'FINISH_LOADING';

export enum PEOPLE_ACTIONS_TYPES {
  SETPEOPLE = 'SET_PEOPLE',
  SET_ERROR = 'SET_ERROR',
  FILTER_BY_NAME = 'FILTER_BY_NAME',
  SET_SELECTED_NATIONALITY = 'SET_SELECTED_NATIONALITY',
  SET_SELECTED_GENDER = 'SET_SELECTED_GENDER',
  CLEAR_FORM = 'CLEAR_FORM',
  CLEAR_DATA = 'CLEAR_DATA',
}
